### ISSUE TITLE
multipart/related support

### ISSUE THREAD

**Issue by jonsterling** [snoyberg/mime-mail#36]
I need embed images in an email, and it seems as if the proper way to do this is through a `multipart/related` block; `multipart/mixed` sort of works, except that the images get shown as attachments in some mail clients.

Before I start burning a bunch of time on this, let me ask the following questions:
1. Does anybody have any prior art?
2. Would a patch that added this to mime-mail be likely to be accepted, and if so, are there any special requirements?

Thanks

**Comment by snoyberg** [comment]
I'm happy to accept a PR, but ideally any such change would not be a breaking API change.

**Comment by jonsterling** [comment]
I don't think it is possible to do without breaking compatibility, but I will ponder it; if I come up with a way, then I'll submit it!

Part of the problem is the mime mail is a recursive structure that accepts various multipart subtypes inside of each other, as opposed to the structure adopted in this library, which is to have a strict Mixed->Alternative hierarchy. 

Kind regards,
JMS

**Comment by snoyberg** [comment]
I'm willing to consider a breaking change, but I'd rather go with a
compatibility layer to avoid breakage if possible.

**Comment by benkolera** [comment]
I hit this today and had a dirty, yet fairly backwards compatible idea. It would involve scanning all attachments and examining them for their content disposition. 

- If the attachment is inline, include it in a multipart/related that also includes the content alternative
- If the attachment is not inline, included it in the outer multipart/mixed.

Thus if you had:
- Alternative 1: Plain
- Alternative 2: Html
- Attachment 1: Content-disposition: Inline Content-Id: foo.jpg
- Attachment 2: Content-disposition: Attachment; filename="bar.pdf"

Then you'd get a MIME tree like:
- Multipart/Mixed
-- Multipart/related 
--- Multipart/Alternative
---- Part: Text
---- Part: Html
---- Part: Foo.gif
-- Part: Bar.pdf

This is pretty unprincipled (text matching on headers = yuck), but it would avoid us having to make parts be able to be nested while still giving the ability to inline some things in a multipart/related. 

The way that it is right now means that inline images in thunderbird inline images can't be referenced by cid: urls in the html since thunderbird adheres to the spec and only allow cid linking within a multipart/related. See https://bugzilla.mozilla.org/show_bug.cgi?id=61815

**Comment by benkolera** [comment]
This was my quick patch that I'm using internally for now: https://github.com/benkolera/mime-mail/commit/5dfd60e47cdafea1198bd756f64dbe1e668bbbe6

It seems to work for my case (if all attachments are inline you just get a multipart/related at the top), doesn't seem like it would cause overly weird behaviour for users and there is no api change. 

@snoyberg If you want this as a PR please let me know and I'll send a PR without the style changes from my automatic stylish haskell refactoring. :)

**Comment by snoyberg** [comment]
I honestly don't have the requisite knowledge of this aspect of MIME to understand the trade-offs here well. I'm leaning much more towards including some kind of a breaking change here, if either you or @jonsterling are interested in going in that direction.

**Comment by benkolera** [comment]
http://en.wikipedia.org/wiki/MIME#Related

The related type is used to specify a bunch of stuff that shouldn't be displayed as a whole but can be combined in some way (usually by cid urls) into what we want the user to see. This is why @jonsterling wants the ability to send a related, as his images are being displayed in his html (and not at all in thunderbird because it only cid links within a related) and also as attachments. 

Mixed is simply saying that we've got a bunch of things of different mime types and they all should be displayed (either inline or as attachments depending on the content disposition).

My quick fix does force a very specific use (though extraordinarily common) use of mixed/related/alternative. It's assuming that every inline thing is part of the same relative, which means that you can't set an inline content disposition inside a mixed (this is a valid use case, but less common than including things inline with html + related + cid urls).

Also because I'm just examining the Maybe FilePath of a part, it does mean that if a user constructs a part with a "Content-disposition: inline" header we wont pick that up as something that should be in the relative, but if the user is guided through the addInlineAttachment constructor (and maybe an additional simpleSendMailRender with a list of alternatives, inline attachments and attachments like in my doctest) then we should be safe to avoid this user confusion.

The more I play with it, the more I think of this easy fix as a nice thing that actually gives a lot of reward for very little change; but that could be just be because I wrote the change and it makes sense to me. 

Take a look at these tests and see if it makes you any more comfortable with the easy fix:
https://github.com/benkolera/mime-mail/blob/master/mime-mail/Doctest.hs

I'm about to ship code with my patched version of mime-mail to production, and I'll let you know how it goes. 

I'm definitely also interested in coming up with a better breaking API change but that will require more thought as it most likely will require Parts to be nested. It is tricky in itself because you don't want the API to offer everything that MIME does; we just need to cover the common cases and it'll take time to research other MIME libs to figure out what the happy medium is.

**Comment by benkolera** [comment]
Oh, sorry! I had not looked at https://github.com/snoyberg/mime-mail/pull/40 until now.

I will take a look at that PR on the weekend after Lambda Jam Brisbane. :D

**Comment by kindaro** [comment]
@jonsterling @benkolera  Is this issue still relevant? Please let me know if I can close it.

**Comment by jonsterling** [comment]
Hi all, i don’t know if the issue is still relevant, but if i am the only person who cared about it, please feel free to close! I think it is more probable for me to get hit by lightning while winning the lottery than for me to be trying to do programmatic emails in code ever again 🤪😅😂

**Comment by kindaro** [comment]
I am going to close the issue for now then, @benkolera please let me know if there are still problems to be solved here.

**Comment by benkolera** [comment]
Yeah, it's safe to close. I haven't had a need for sending emails from haskell in a while. If someone hits it again this closed ticket can be a guidepost for them. 🙂 

I do know that there is a production system still running with a 4 year old fork of mime-mail with the fix that I proposed above in it ( https://github.com/iseek/mime-mail/commit/5dfd60e47cdafea1198bd756f64dbe1e668bbbe6 ), but I'm not sure whether things have improved enough around that fork to make it no longer necessary.
